Move osaka mzr to new folder
IBM-Cloud/kube-samples pull request #123
Opened 2021-03-30 17:33 UTC by Rachael-Graham

2021-04-05 19:35 UTC, bradbehle requested changes

2021-04-05 20:10 UTC, Rachael-Graham commented on calico-policies/private-network-isolation/calico-v3/jp-osa/generic-privatehostendpoint.yaml
> +# List all worker node names on your private network.
@bradbehle thoughts on keeping it for 3.11 clusters until those are completely unsupported June 06?

2021-04-06 13:15 UTC, bradbehle commented on calico-policies/private-network-isolation/calico-v3/jp-osa/generic-privatehostendpoint.yaml
> +# List all worker node names on your private network.
I forgot about ROKS 3.11 clusters.  We should leave these in, but maybe we can put a note in the https://github.com/IBM-Cloud/kube-samples/blob/master/calico-policies/private-network-isolation/README.md that they are only needed for ROKS 3.11 (that all other IKS/ROKS releases now automatically create private host endpoints).  And then add a comment in the generic-privatehostendpoint.yaml files themselves saying the same, so it's clear that most customers can ignore these?

2021-04-06 14:16 UTC, bradbehle approved these changes

2021-04-06 14:17 UTC, bradbehle commented on calico-policies/private-network-isolation/calico-v3/jp-osa/generic-privatehostendpoint.yaml
> +# List all worker node names on your private network.
Looks great, thanks.  Approved

2021-04-06 14:48 UTC, merged