ip-table-update
IBM-Cloud/kube-samples pull request #184
Opened 2022-02-16 16:18 UTC by alchemyDocs

There are updates to the IP tables. Review the latest changes.

2022-03-02 15:50 UTC, bradbehle requested changes
We need to do more testing of these changes, and probably have some of the squad leads meet to sign off on these, before they are merged

2022-04-11 19:58 UTC, derekpoindexter approved these changes

2022-04-11 19:59 UTC, derekpoindexter commented
@bradbehle - can you take a look at this one again - i updated the script to pull only microservice clusters for the "control-plane-ip" files

2022-04-13 02:51 UTC, bradbehle commented
These look right as far as the general size of the lists and number of subnets.  Also, I do think this is right to put only the microservices tugboat/control plane subnets in the control-plane-ips based on the recent doc clarifications we made (or are in the process of making), and put the full control plane IP subnet lists in the iam-firewall-ips lists.

Unfortunately, I don't have a good way to verify the control plane subnets.  Tomorrow I should spot check a few regions to make sure they look right

2022-04-13 03:43 UTC, bradbehle commented on control-plane-ips/control-plane-ips-dal.txt
> +52.116.235.224/28
Verified this

2022-04-13 03:45 UTC, bradbehle commented on control-plane-ips/control-plane-ips-fra.txt
> -169.51.193.0/24
Verified this

2022-04-13 03:46 UTC, bradbehle commented on control-plane-ips/control-plane-ips-lon.txt
> +158.176.95.0/27
Verified this

2022-04-13 03:48 UTC, bradbehle commented on control-plane-ips/control-plane-ips-osa.txt
> -163.73.66.128/27
Verified this

2022-04-13 03:50 UTC, bradbehle commented on control-plane-ips/control-plane-ips-sao.txt
>  169.57.219.16/28
Verified this

2022-04-13 03:50 UTC, bradbehle commented on control-plane-ips/control-plane-ips-syd.txt
> -168.1.212.128/25
Verified this

2022-04-13 03:52 UTC, bradbehle commented on control-plane-ips/control-plane-ips-tok.txt
> -169.56.143.0/26
Verified this

2022-04-13 03:54 UTC, bradbehle commented on control-plane-ips/control-plane-ips-tor.txt
> -169.55.148.128/25
Verified this

2022-04-13 03:56 UTC, bradbehle commented on control-plane-ips/control-plane-ips-wdc.txt
> +52.117.100.64/27
Verified this

2022-04-13 03:59 UTC, bradbehle approved these changes
I was able to find a way to verify the control-plane-ips, they are correct, so this looks good.  Thanks for generating these

2022-04-13 12:24 UTC, merged