run cis-kube-benchmark test in a privileged namespace
IBM-Cloud/kube-samples pull request #220
Opened 2022-11-11 15:04 UTC by Evan-Reilly

See associated change in the kubernetes-pipeline repo: https://github.ibm.com/alchemy-containers/kubernetes-pipeline/pull/5940/files

2022-11-15 22:35 UTC, rtheis requested changes

2022-11-15 22:35 UTC, rtheis commented on cis-kube-benchmark/cis-1.5/ibm/ibm-kube-bench-test-namespace.yaml
> +---
Per https://cloud.ibm.com/docs/containers?topic=containers-cis-benchmark#cis-worker-test, we need this to be in the `job-node.yaml` file.

2022-11-16 15:56 UTC, rtheis requested changes

2022-11-16 15:58 UTC, rtheis commented on cis-kube-benchmark/cis-1.5/ibm/job-node.yaml
> +  namespace: ibm-kube-bench-test
Thinking more about this, it probably make sense to set the namespace everywhere since we are adding the pod security labels.

2022-11-16 19:46 UTC, rtheis approved these changes
/lgtm
/approved

2022-11-17 14:18 UTC, derekpoindexter approved these changes

2022-11-17 22:16 UTC, rtheis approved these changes
/lgtm
/approved

2022-11-21 17:52 UTC, bradbehle approved these changes

2022-11-21 18:55 UTC, merged