Master
IBM-Cloud/kube-samples pull request #227
Opened 2023-01-20 01:14 UTC by knperi

Adding new  Mezmo (LogDNA) Public, Private and Ingestion endpoints

2023-01-20 01:16 UTC, knperi commented
@bradbehle @derekpoindexter @kersten1 

Please can you review the changes I have made. The upcoming changes are documented [here](https://test.cloud.ibm.com/docs/log-analysis?topic=log-analysis-endpoints)

2023-01-20 17:24 UTC, bradbehle requested changes
What you have here looks right, just a few things I noticed:

1. Please remove those binary .DS_Store files from the commit/PR
2. These IPs I think should also be in the allow-private-services.yaml and allow-public-services.yaml files (the non "pod" policies) since the old/existing LogDNA IPs are in both
3. Do you know if IKS/ROKS clusters with workers in Chennai use the jp-tok or Chennai addresses?  If they do use the Chennai specific ones, then the new Chennai specific IPs should go in the jp-tok policies (along with the jp-tok specific IPs)

2023-01-20 19:12 UTC, knperi commented
@bradbehle Removed .DS_Store files and modified allow-<privare|public>-services.yaml files as suggested. Please review.

2023-01-20 19:29 UTC, bradbehle requested changes
Looks like one typo, and still two .DS_Store binaries to remove

2023-01-20 19:29 UTC, bradbehle commented on calico-policies/public-network-isolation/jp-tok/allow-public-services-pods.yaml
> +    prEtocol: TCP
typo I assume?

2023-01-20 19:55 UTC, knperi commented
@bradbehle Sorry for the typo. Fixed and removed the other binary files

2023-01-20 20:06 UTC, bradbehle requested changes

2023-01-20 20:06 UTC, bradbehle commented on calico-policies/public-network-isolation/eu-de/allow-public-services-pods.yaml
> +      # New IP addresses added by perik@us.ibm.com 1/19/2023
In the docs here: https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-endpoints  these IPs are listed as for ca-tor, so I think there might have been a copy/paste error here?

2023-01-20 20:06 UTC, bradbehle commented on calico-policies/public-network-isolation/eu-de/allow-public-services.yaml
> +      # New IP addresses added by perik@us.ibm.com 1/19/2023
In the docs here: https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-endpoints  these IPs are listed as for ca-tor, so I think there might have been a copy/paste error here?

2023-01-20 20:59 UTC, knperi commented
@bradbehle Yes. It was a cut and paste error.

2023-01-23 02:20 UTC, bradbehle approved these changes

2023-01-23 08:52 UTC, mihivagyok reviewed
Please use better PR name in the future. Also, are you sure you want your email address in the files? By this, anyone can read it easily, and the address could be added to be a spam database. We could use git history instead. Thanks!

2023-01-23 13:36 UTC, derekpoindexter approved these changes

2023-01-23 15:03 UTC, closed without merging